<?php
/**
 * Adds remaining menu-linked sub-actions to the generated module controllers.
 * Same insert-before-final-brace approach as add_menu_actions.php; safe to re-run.
 */

$patches = [];

$patches['TraineeNameCardsController.php'] = <<<'EOT'

    /**
     * Bulk generation - menu alias for the card list
     */
    public function printBatch()
    {
        return $this->redirect(['action' => 'index']);
    }
EOT;

$patches['TraineeSubmissionDocumentsController.php'] = <<<'EOT'

    /**
     * Progress tracking - submission counts by status
     */
    public function progress()
    {
        $query = $this->TraineeSubmissionDocuments->find();
        $byStatus = $query
            ->select([
                'master_document_submission_status_id',
                'doc_count' => $query->func()->count('*'),
            ])
            ->group('master_document_submission_status_id')
            ->enableHydration(false)
            ->toArray();
        $total = $this->TraineeSubmissionDocuments->find()->count();
        $this->set(compact('byStatus', 'total'));
    }

    /**
     * Cost management - document cost records
     */
    public function costs()
    {
        $conn = \Cake\Datasource\ConnectionManager::get('cms_tmm_trainee_accountings');
        $costs = \Cake\ORM\TableRegistry::getTableLocator()
            ->get('TraineeDocumentCosts', ['connection' => $conn])
            ->find()
            ->order(['id' => 'DESC'])
            ->limit(500)
            ->toArray();
        $this->set(compact('costs'));
    }
EOT;

$patches['TicketsController.php'] = <<<'EOT'

    /**
     * Departure management - menu alias for the ticket list
     */
    public function departures()
    {
        return $this->redirect(['action' => 'index']);
    }

    /**
     * Transit routes - trainee flights listing
     */
    public function transit()
    {
        $conn = \Cake\Datasource\ConnectionManager::get('cms_tmm_trainee_document_ticketings');
        $flights = \Cake\ORM\TableRegistry::getTableLocator()
            ->get('TraineeFlights', ['connection' => $conn])
            ->find()
            ->order(['id' => 'DESC'])
            ->limit(500)
            ->toArray();
        $this->set(compact('flights'));
    }

    /**
     * Ticket cost tracking - tickets with prices
     */
    public function costs()
    {
        $this->paginate = ['order' => ['Tickets.id' => 'DESC']];
        $tickets = $this->paginate($this->Tickets);
        $this->set(compact('tickets'));
        $this->render('index');
    }
EOT;

$patches['ChartOfAccountsController.php'] = <<<'EOT'

    /**
     * Account hierarchy grouped by account type
     */
    public function hierarchy()
    {
        $accounts = $this->ChartOfAccounts->find()
            ->order(['type' => 'ASC', 'code' => 'ASC'])
            ->enableHydration(false)
            ->toArray();
        $grouped = [];
        foreach ($accounts as $account) {
            $type = $account['type'] ?: '(untyped)';
            $grouped[$type][] = $account;
        }
        $this->set(compact('grouped'));
    }
EOT;

$patches['JournalsController.php'] = <<<'EOT'

    /**
     * Auto-generated entries - menu alias for the journal list
     */
    public function autoGenerated()
    {
        return $this->redirect(['action' => 'index']);
    }

    /**
     * Manual adjustments - menu alias for the journal list
     */
    public function adjustments()
    {
        return $this->redirect(['action' => 'index']);
    }
EOT;

foreach ($patches as $file => $code) {
    $path = __DIR__ . '/src/Controller/' . $file;
    $src = file_get_contents($path);
    if ($src === false) {
        echo "MISSING $file\n";
        continue;
    }
    preg_match('/public function (\w+)\(/', $code, $m);
    if (strpos($src, 'function ' . $m[1] . '(') !== false) {
        echo "skip   $file\n";
        continue;
    }
    $pos = strrpos($src, '}');
    $src = substr($src, 0, $pos) . $code . "\n}\n";
    file_put_contents($path, $src);
    echo "patched $file\n";
}
echo "done\n";
