-- Grant tmm-accounting (role 7) full CRUD on its accounting modules.
-- granted_actions='*' only expands to [menu action, index, view] in
-- AppController::getMenuRolePermissions(), so add/edit/delete were denied
-- (e.g. the "+ Add Installment Payment" button on /dashboard/accounting).

-- IMPORTANT: menus 86/89/92 are parent containers (they have child menus
-- assigned to the role), so getMenuRolePermissions() ignores their
-- granted_actions. The explicit lists must live on CHILD menus (87, 90, 93).

USE cms_authentication_authorization;

UPDATE role_menus
SET granted_actions = 'index,view,add,edit,delete,tracking,receipts,setOwingCost,exportCsv,exportExcel,printReport,exportPdf,processFlow',
    modified = NOW()
WHERE role_id = 7 AND menu_id = 87;  -- Payment Tracking (child of Trainee Installments)

UPDATE role_menus
SET granted_actions = 'index,view,add,edit,delete,hierarchy', modified = NOW()
WHERE role_id = 7 AND menu_id = 90;  -- Manage COA (child of Chart of Accounts)

UPDATE role_menus
SET granted_actions = 'index,view,add,edit,delete,autoGenerated,adjustments', modified = NOW()
WHERE role_id = 7 AND menu_id = 93;  -- Auto-Generated Entries (child of Journal Entries)

-- Verify
SELECT rm.menu_id, m.title, rm.granted_actions
FROM role_menus rm
JOIN cms_masters.menus m ON m.id = rm.menu_id
WHERE rm.role_id = 7 AND rm.menu_id IN (86, 87, 89, 90, 92, 93);
