<?php
/**
 * A list, laid out for printing.
 *
 * @var \App\View\AppView $this
 * @var string $title
 * @var array $headers Column headings.
 * @var array $rows Cells, already laid out by ExportTrait::doExportPrint().
 */
?>
<div class="print-header">
    <h1><?= h($title) ?></h1>
    <div class="print-info">
        Total Records: <strong><?= count($rows) ?></strong>
    </div>
</div>

<table>
    <thead>
        <tr>
            <?php foreach ($headers as $header): ?>
                <th><?= h($header) ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php
        /**
         * The cells arrive already laid out by ExportTrait::doExportPrint(),
         * so this page, the CSV and the spreadsheet say the same thing.
         *
         * They were worked out here before, and only FrozenTime was named: a
         * date printed as the locale's short form - 5/10/26, which is either
         * the tenth of May or the fifth of October - while the same column in
         * the CSV read 2026-05-10. A value behind a dot was printed raw.
         */
        ?>
        <?php foreach ($rows as $cells): ?>
            <tr>
                <?php foreach ($cells as $cell): ?>
                    <td><?= h($cell) ?></td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="print-footer">
    <strong><?= __('Generated by TMM Apprentice Management System') ?></strong>
    <div class="company-info">TMM Apprentice Management System</div>
    <div class="company-info">Printed on: <?= date('l, d F Y H:i:s') ?></div>
</div>

