<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Datasource\ConnectionManager;

/**
 * Journals Controller
 *
 * Double-entry general ledger with three entry modes:
 *   - add()          : manual journal (free-form debit/credit lines)
 *   - adjustments()  : manual adjustment (same form, ADJ- reference)
 *   - autoGenerated(): entries generated from source cost/price records
 *                      (installment payments, tickets, document costs),
 *                      each mapped to the matching Chart of Accounts entries.
 *
 * @property \App\Model\Table\JournalsTable $Journals
 */
class JournalsController extends AppController
{
    /** Accounting database (journals + journal_details + chart_of_accounts) */
    const ACC_DB = 'cms_tmm_trainee_accountings';

    /**
     * Source-record -> COA mapping for auto-generated journals.
     * Each source event debits one account and credits another (balanced).
     */
    protected function sourceMappings()
    {
        return [
            'installment' => [
                'label' => __('Training Fee Received'),
                'icon' => 'fa-graduation-cap',
                'ref_prefix' => 'INST',
                'debit_code' => '1000',   // Cash
                'credit_code' => '4000',  // Training Revenue
            ],
            'ticket' => [
                'label' => __('Flight Ticket Cost'),
                'icon' => 'fa-plane',
                'ref_prefix' => 'TKT',
                'debit_code' => '5200',   // Transportation & Ticketing Expense
                'credit_code' => '2000',  // Accounts Payable
            ],
            'doc_cost' => [
                'label' => __('Document Processing Cost'),
                'icon' => 'fa-file-text-o',
                'ref_prefix' => 'DOC',
                'debit_code' => '5100',   // Document Expense
                'credit_code' => '1000',  // Cash
            ],
        ];
    }

    public function index()
    {
        $filterStatus = (string)$this->request->getQuery('status');
        $query = $this->Journals->find();
        if (in_array($filterStatus, ['Draft', 'Posted', 'Void'], true)) {
            $query->where(['status' => $filterStatus]);
        } else {
            $filterStatus = '';
        }

        $this->paginate = ['order' => ['Journals.id' => 'DESC']];
        $journals = $this->paginate($query);

        $summary = ['total' => 0, 'Draft' => 0, 'Posted' => 0, 'Void' => 0, 'postedDebit' => 0, 'postedCredit' => 0];
        try {
            $conn = ConnectionManager::get(self::ACC_DB);
            foreach ($conn->execute(
                'SELECT status, COUNT(*) AS total,
                        COALESCE(SUM(total_debit), 0) AS debit,
                        COALESCE(SUM(total_credit), 0) AS credit
                 FROM journals GROUP BY status'
            )->fetchAll('assoc') as $row) {
                $summary[$row['status']] = (int)$row['total'];
                $summary['total'] += (int)$row['total'];
                if ($row['status'] === 'Posted') {
                    $summary['postedDebit'] = (float)$row['debit'];
                    $summary['postedCredit'] = (float)$row['credit'];
                }
            }
        } catch (\Exception $e) {
        }

        $this->set(compact('journals', 'summary', 'filterStatus'));
    }

    public function view($id = null)
    {
        $journal = $this->Journals->get($id);

        // Double-entry lines with account names
        $lines = [];
        try {
            $lines = ConnectionManager::get(self::ACC_DB)->execute(
                'SELECT jd.debit, jd.credit, jd.description,
                        coa.code, coa.name, coa.type
                 FROM journal_details jd
                 JOIN chart_of_accounts coa ON coa.id = jd.chart_of_account_id
                 WHERE jd.journal_id = ?
                 ORDER BY jd.id',
                [(int)$id]
            )->fetchAll('assoc');
        } catch (\Exception $e) {
        }

        $this->set(compact('journal', 'lines'));
    }

    /**
     * Manual journal entry - free-form balanced debit/credit lines.
     */
    public function add()
    {
        return $this->manualEntry('manual');
    }

    /**
     * Manual adjustment - same double-entry form, tagged as an adjustment.
     */
    public function adjustments()
    {
        return $this->manualEntry('adjustment');
    }

    /**
     * Shared manual double-entry form (add + adjustments).
     */
    protected function manualEntry($mode)
    {
        $isAdjustment = ($mode === 'adjustment');

        if ($this->request->is('post')) {
            $data = $this->request->getData();
            $lines = isset($data['lines']) ? $data['lines'] : [];

            $clean = [];
            $totalDebit = 0;
            $totalCredit = 0;
            foreach ($lines as $line) {
                $accountId = (int)(isset($line['chart_of_account_id']) ? $line['chart_of_account_id'] : 0);
                $debit = (float)(isset($line['debit']) ? $line['debit'] : 0);
                $credit = (float)(isset($line['credit']) ? $line['credit'] : 0);
                if (!$accountId || ($debit <= 0 && $credit <= 0)) {
                    continue;
                }
                $clean[] = [
                    'chart_of_account_id' => $accountId,
                    'debit' => $debit,
                    'credit' => $credit,
                    'description' => isset($line['description']) ? trim((string)$line['description']) : null,
                ];
                $totalDebit += $debit;
                $totalCredit += $credit;
            }

            if (count($clean) < 2) {
                $this->Flash->error(__('A journal needs at least two lines (a debit and a credit).'));
            } elseif (round($totalDebit, 2) !== round($totalCredit, 2)) {
                $this->Flash->error(__('The entry is not balanced: debit Rp {0} vs credit Rp {1}.',
                    number_format($totalDebit, 0, ',', '.'), number_format($totalCredit, 0, ',', '.')));
            } else {
                $refPrefix = $isAdjustment ? 'ADJ' : 'JRN';
                $header = [
                    'transaction_date' => !empty($data['transaction_date']) ? $data['transaction_date'] : date('Y-m-d'),
                    'reference_no' => !empty($data['reference_no']) ? $data['reference_no'] : $this->nextReference($refPrefix),
                    'description' => isset($data['description']) ? trim((string)$data['description']) : null,
                    'status' => (isset($data['status']) && in_array($data['status'], ['Draft', 'Posted'])) ? $data['status'] : 'Posted',
                ];
                $journalId = $this->writeJournal($header, $clean);
                if ($journalId) {
                    $this->Flash->success($isAdjustment
                        ? __('Adjustment entry {0} saved.', $header['reference_no'])
                        : __('Journal entry {0} saved.', $header['reference_no']));

                    return $this->redirect(['action' => 'view', $journalId]);
                }
                $this->Flash->error(__('The journal could not be saved. Please, try again.'));
            }
        }

        $accounts = $this->accountOptions();
        $this->set(compact('accounts', 'isAdjustment'));
        $this->set('pageTitle', $isAdjustment ? __('Manual Adjustment') : __('Manual Journal Entry'));
        $this->render('manual_entry');
    }

    /**
     * Auto-generated entries - scan source cost/price records and create the
     * matching double-entry journals (each mapped to its COA accounts).
     */
    public function autoGenerated()
    {
        $coa = $this->coaByCode();

        if ($this->request->is('post')) {
            $onlyType = (string)$this->request->getData('source_type');
            $pending = $this->pendingSources($onlyType ?: null);
            $created = 0;
            foreach ($pending as $item) {
                $map = $item['map'];
                if (!isset($coa[$map['debit_code']], $coa[$map['credit_code']])) {
                    continue; // required COA account missing - skip safely
                }
                $header = [
                    'transaction_date' => $item['date'],
                    'reference_no' => $item['reference_no'],
                    'description' => $item['description'],
                    'status' => 'Posted',
                ];
                $lines = [
                    ['chart_of_account_id' => $coa[$map['debit_code']]['id'], 'debit' => $item['amount'], 'credit' => 0, 'description' => $item['description']],
                    ['chart_of_account_id' => $coa[$map['credit_code']]['id'], 'debit' => 0, 'credit' => $item['amount'], 'description' => $item['description']],
                ];
                if ($this->writeJournal($header, $lines)) {
                    $created++;
                }
            }
            if ($created) {
                $this->Flash->success(__('{0} journal entr{1} generated from source records.',
                    $created, $created === 1 ? 'y' : 'ies'));
            } else {
                $this->Flash->error(__('Nothing to generate - all source records are already journalized (or a required account is missing).'));
            }

            return $this->redirect(['action' => 'autoGenerated']);
        }

        // GET: list pending (un-journalized) source records + already generated
        $pending = $this->pendingSources();
        $pendingByType = [];
        $pendingTotal = 0;
        foreach ($pending as $item) {
            $pendingByType[$item['type']][] = $item;
            $pendingTotal += $item['amount'];
        }
        $generatedCount = (int)$this->scalar('SELECT COUNT(*) FROM journals WHERE reference_no REGEXP \'^(INST|TKT|DOC)-\'');
        $mappings = $this->sourceMappings();

        $this->set(compact('pendingByType', 'pendingTotal', 'generatedCount', 'mappings', 'coa'));
    }

    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $journal = $this->Journals->get($id);
        try {
            ConnectionManager::get(self::ACC_DB)
                ->execute('DELETE FROM journal_details WHERE journal_id = ?', [(int)$id]);
        } catch (\Exception $e) {
        }
        if ($this->Journals->delete($journal)) {
            $this->Flash->success(__('The Journal has been deleted.'));
        } else {
            $this->Flash->error(__('The Journal could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    /**
     * Write a journal header + its double-entry lines in one transaction.
     * Returns the new journal id, or false on failure.
     */
    protected function writeJournal(array $header, array $lines)
    {
        $conn = ConnectionManager::get(self::ACC_DB);
        $totalDebit = 0;
        $totalCredit = 0;
        foreach ($lines as $line) {
            $totalDebit += (float)$line['debit'];
            $totalCredit += (float)$line['credit'];
        }

        $createdBy = null;
        try {
            if (isset($this->Auth) && is_object($this->Auth)) {
                $createdBy = $this->Auth->user('id');
            }
        } catch (\Throwable $e) {
        }

        try {
            return $conn->transactional(function ($conn) use ($header, $lines, $totalDebit, $totalCredit, $createdBy) {
                $conn->insert('journals', [
                    'transaction_date' => $header['transaction_date'],
                    'reference_no' => $header['reference_no'],
                    'description' => $header['description'],
                    'total_debit' => $totalDebit,
                    'total_credit' => $totalCredit,
                    'status' => $header['status'],
                    'created_by' => $createdBy,
                ]);
                $journalId = (int)$conn->execute('SELECT LAST_INSERT_ID()')->fetch()[0];
                foreach ($lines as $line) {
                    $conn->insert('journal_details', [
                        'journal_id' => $journalId,
                        'chart_of_account_id' => $line['chart_of_account_id'],
                        'debit' => $line['debit'],
                        'credit' => $line['credit'],
                        'description' => isset($line['description']) ? $line['description'] : null,
                    ]);
                }

                return $journalId;
            });
        } catch (\Exception $e) {
            $this->log('writeJournal failed: ' . $e->getMessage(), 'error');

            return false;
        }
    }

    /**
     * Source cost/price records that do not yet have a journal (by reference_no).
     */
    protected function pendingSources($onlyType = null)
    {
        $maps = $this->sourceMappings();
        $existing = [];
        try {
            foreach (ConnectionManager::get(self::ACC_DB)
                ->execute('SELECT reference_no FROM journals WHERE reference_no IS NOT NULL')
                ->fetchAll('assoc') as $row) {
                $existing[$row['reference_no']] = true;
            }
        } catch (\Exception $e) {
        }

        $pending = [];

        // 1. Installment payments -> Training Fee Received
        if ($onlyType === null || $onlyType === 'installment') {
            $map = $maps['installment'];
            $rows = $this->rows(self::ACC_DB,
                'SELECT i.id, i.payment_amount AS amount, i.payment_date,
                        t.name AS trainee
                 FROM trainee_installments i
                 LEFT JOIN cms_tmm_trainees.trainees t ON t.id = i.trainee_id
                 WHERE i.payment_amount > 0');
            foreach ($rows as $r) {
                $ref = $map['ref_prefix'] . '-' . $r['id'];
                if (isset($existing[$ref])) {
                    continue;
                }
                $pending[] = [
                    'type' => 'installment', 'map' => $map, 'reference_no' => $ref,
                    'amount' => (float)$r['amount'],
                    'date' => $r['payment_date'] ?: date('Y-m-d'),
                    'description' => $map['label'] . ' - ' . ($r['trainee'] ?: ('Trainee #' . $r['id'])),
                    'subject' => $r['trainee'] ?: ('#' . $r['id']),
                ];
            }
        }

        // 2. Tickets -> Flight Ticket Cost
        if ($onlyType === null || $onlyType === 'ticket') {
            $map = $maps['ticket'];
            $rows = $this->rows('cms_tmm_trainee_document_ticketings',
                'SELECT tk.id, tk.total_price AS amount, tk.ticket_number,
                        t.name AS trainee
                 FROM tickets tk
                 LEFT JOIN cms_tmm_trainees.trainees t ON t.id = tk.trainee_id
                 WHERE tk.total_price > 0');
            foreach ($rows as $r) {
                $ref = $map['ref_prefix'] . '-' . $r['id'];
                if (isset($existing[$ref])) {
                    continue;
                }
                $pending[] = [
                    'type' => 'ticket', 'map' => $map, 'reference_no' => $ref,
                    'amount' => (float)$r['amount'],
                    'date' => date('Y-m-d'),
                    'description' => $map['label'] . ' - ' . ($r['ticket_number'] ?: ('Ticket #' . $r['id']))
                        . ($r['trainee'] ? ' (' . $r['trainee'] . ')' : ''),
                    'subject' => $r['trainee'] ?: ($r['ticket_number'] ?: ('#' . $r['id'])),
                ];
            }
        }

        // 3. Document costs -> Document Processing Cost (only the paid portion)
        if ($onlyType === null || $onlyType === 'doc_cost') {
            $map = $maps['doc_cost'];
            $rows = $this->rows(self::ACC_DB,
                'SELECT c.id, c.paid_amount AS amount, c.document_type, c.payment_date,
                        t.name AS trainee
                 FROM trainee_document_costs c
                 LEFT JOIN cms_tmm_trainees.trainees t ON t.id = c.trainee_id
                 WHERE c.paid_amount > 0');
            foreach ($rows as $r) {
                $ref = $map['ref_prefix'] . '-' . $r['id'];
                if (isset($existing[$ref])) {
                    continue;
                }
                $pending[] = [
                    'type' => 'doc_cost', 'map' => $map, 'reference_no' => $ref,
                    'amount' => (float)$r['amount'],
                    'date' => $r['payment_date'] ?: date('Y-m-d'),
                    'description' => $map['label'] . ' - ' . ucfirst((string)$r['document_type'])
                        . ($r['trainee'] ? ' (' . $r['trainee'] . ')' : ''),
                    'subject' => $r['trainee'] ?: ('#' . $r['id']),
                ];
            }
        }

        return $pending;
    }

    /**
     * COA options for the manual form: [id => "1000 - Cash (Asset)"]
     */
    protected function accountOptions()
    {
        $options = [];
        try {
            foreach (ConnectionManager::get(self::ACC_DB)
                ->execute('SELECT id, code, name, type FROM chart_of_accounts WHERE is_active = 1 ORDER BY code')
                ->fetchAll('assoc') as $row) {
                $options[$row['id']] = $row['code'] . ' - ' . $row['name'] . ' (' . $row['type'] . ')';
            }
        } catch (\Exception $e) {
        }

        return $options;
    }

    /**
     * COA indexed by code: ['1000' => ['id'=>1,'name'=>'Cash', ...]]
     */
    protected function coaByCode()
    {
        $map = [];
        try {
            foreach (ConnectionManager::get(self::ACC_DB)
                ->execute('SELECT id, code, name, type FROM chart_of_accounts')
                ->fetchAll('assoc') as $row) {
                $map[$row['code']] = ['id' => (int)$row['id'], 'name' => $row['name'], 'type' => $row['type']];
            }
        } catch (\Exception $e) {
        }

        return $map;
    }

    protected function nextReference($prefix)
    {
        $year = date('Y');
        $count = (int)$this->scalar(
            'SELECT COUNT(*) FROM journals WHERE reference_no LIKE ?',
            [$prefix . '-' . $year . '-%']
        );

        return sprintf('%s-%s-%04d', $prefix, $year, $count + 1);
    }

    protected function rows($db, $sql, $params = [])
    {
        try {
            return ConnectionManager::get($db)->execute($sql, $params)->fetchAll('assoc');
        } catch (\Exception $e) {
            return [];
        }
    }

    protected function scalar($sql, $params = [])
    {
        try {
            $row = ConnectionManager::get(self::ACC_DB)->execute($sql, $params)->fetch();

            return $row ? $row[0] : 0;
        } catch (\Exception $e) {
            return 0;
        }
    }
}
