<?php
/**
 * Auto-Generated Journal Entries - review source records and post them
 *
 * @var \App\View\AppView $this
 * @var array $pendingByType   [type => [items]]
 * @var float $pendingTotal
 * @var int $generatedCount
 * @var array $mappings        source type -> COA mapping meta
 * @var array $coa             [code => ['id','name','type']]
 */
$this->assign('title', 'Auto-Generated Journals');

$money = function ($amount) {
    return 'Rp ' . number_format((float)$amount, 0, ',', '.');
};

$pendingCount = 0;
foreach ($pendingByType as $items) {
    $pendingCount += count($items);
}
?>

<div class="autogen-page">
    <div class="page-header">
        <div>
            <h2><i class="fa fa-magic"></i> <?= __('Auto-Generated Journals') ?></h2>
            <p class="text-muted"><?= __('Turn source cost/price records into balanced double-entry journals, matched to the Chart of Accounts') ?></p>
        </div>
        <div class="page-header-actions">
            <?= $this->Html->link('<i class="fa fa-pencil-square-o"></i> ' . __('Manual Entry'),
                ['action' => 'add'], ['escape' => false, 'class' => 'btn btn-sm btn-outline-secondary']) ?>
            <?= $this->Html->link('<i class="fa fa-book"></i> ' . __('All Journals'),
                ['action' => 'index'], ['escape' => false, 'class' => 'btn btn-sm btn-outline-secondary']) ?>
        </div>
    </div>

    <!-- Summary strip -->
    <div class="summary-strip">
        <div class="summary-card summary-pending">
            <span class="summary-number"><?= number_format($pendingCount) ?></span>
            <span class="summary-label"><i class="fa fa-hourglass-half"></i> <?= __('Pending Records') ?></span>
        </div>
        <div class="summary-card summary-value">
            <span class="summary-number summary-money"><?= $money($pendingTotal) ?></span>
            <span class="summary-label"><i class="fa fa-money"></i> <?= __('Pending Value') ?></span>
        </div>
        <div class="summary-card summary-done">
            <span class="summary-number"><?= number_format($generatedCount) ?></span>
            <span class="summary-label"><i class="fa fa-check-circle"></i> <?= __('Already Generated') ?></span>
        </div>
    </div>

    <!-- COA mapping reference -->
    <div class="card">
        <div class="card-header"><h4><i class="fa fa-exchange"></i> <?= __('How each source maps to the Chart of Accounts') ?></h4></div>
        <div class="card-body">
            <div class="mapping-grid">
                <?php foreach ($mappings as $type => $map): ?>
                    <?php
                    $debit = isset($coa[$map['debit_code']]) ? $coa[$map['debit_code']] : null;
                    $credit = isset($coa[$map['credit_code']]) ? $coa[$map['credit_code']] : null;
                    $ready = $debit && $credit;
                    ?>
                    <div class="mapping-card <?= $ready ? '' : 'mapping-broken' ?>">
                        <div class="mapping-title"><i class="fa <?= $map['icon'] ?>"></i> <?= h($map['label']) ?></div>
                        <?php if ($ready): ?>
                            <div class="mapping-line">
                                <span class="dc dc-debit"><?= __('Dr') ?></span>
                                <span><?= h($map['debit_code']) ?> <?= h($debit['name']) ?></span>
                            </div>
                            <div class="mapping-line">
                                <span class="dc dc-credit"><?= __('Cr') ?></span>
                                <span><?= h($map['credit_code']) ?> <?= h($credit['name']) ?></span>
                            </div>
                        <?php else: ?>
                            <div class="mapping-warn">
                                <i class="fa fa-exclamation-triangle"></i>
                                <?= __('Missing account {0} or {1} in the Chart of Accounts.', $map['debit_code'], $map['credit_code']) ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <?php if ($pendingCount > 0): ?>
        <div class="generate-bar">
            <span><strong><?= number_format($pendingCount) ?></strong> <?= __('source records ready to journalize') ?> (<?= $money($pendingTotal) ?>)</span>
            <?= $this->Form->create(null, ['url' => ['action' => 'autoGenerated']]) ?>
                <?= $this->Form->hidden('source_type', ['value' => '']) ?>
                <?= $this->Form->button('<i class="fa fa-bolt"></i> ' . __('Generate All'),
                    ['escapeTitle' => false, 'class' => 'btn btn-success',
                     'confirm' => __('Generate {0} posted journal entries from these source records?', $pendingCount)]) ?>
            <?= $this->Form->end() ?>
        </div>

        <?php foreach ($pendingByType as $type => $items): ?>
            <?php $map = $mappings[$type]; ?>
            <div class="card">
                <div class="card-header header-flex">
                    <h4><i class="fa <?= $map['icon'] ?>"></i> <?= h($map['label']) ?> <span class="count-chip"><?= count($items) ?></span></h4>
                    <?= $this->Form->create(null, ['url' => ['action' => 'autoGenerated']]) ?>
                        <?= $this->Form->hidden('source_type', ['value' => $type]) ?>
                        <?= $this->Form->button('<i class="fa fa-bolt"></i> ' . __('Generate These'),
                            ['escapeTitle' => false, 'class' => 'btn btn-sm btn-success']) ?>
                    <?= $this->Form->end() ?>
                </div>
                <div class="card-body">
                    <div class="table-scroll-wrapper" style="overflow-x:auto;">
                        <table class="pending-table">
                            <thead>
                                <tr>
                                    <th><?= __('Reference') ?></th>
                                    <th><?= __('Subject') ?></th>
                                    <th><?= __('Date') ?></th>
                                    <th><?= __('Entry') ?></th>
                                    <th class="text-right"><?= __('Amount') ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($items as $item): ?>
                                <tr>
                                    <td><code class="ref-code"><?= h($item['reference_no']) ?></code></td>
                                    <td><?= h($item['subject']) ?></td>
                                    <td class="text-muted"><?= h($item['date']) ?></td>
                                    <td class="entry-cell">
                                        <span class="dc dc-debit"><?= __('Dr') ?></span> <?= h($map['debit_code']) ?>
                                        <i class="fa fa-long-arrow-right"></i>
                                        <span class="dc dc-credit"><?= __('Cr') ?></span> <?= h($map['credit_code']) ?>
                                    </td>
                                    <td class="text-right"><strong><?= $money($item['amount']) ?></strong></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <div class="card">
            <div class="empty-state">
                <i class="fa fa-check-circle fa-4x"></i>
                <h4><?= __('All source records are journalized.') ?></h4>
                <p class="text-muted"><?= __('Every installment payment, ticket and document cost already has a matching journal entry. New cost/price records will appear here automatically.') ?></p>
                <?= $this->Html->link('<i class="fa fa-book"></i> ' . __('View Journals'),
                    ['action' => 'index'], ['escape' => false, 'class' => 'btn btn-primary']) ?>
            </div>
        </div>
    <?php endif; ?>
</div>

<style>
.autogen-page .page-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 20px;
    flex-wrap: wrap;
    gap: 10px;
}
.autogen-page .page-header h2 { margin: 0 0 5px 0; }
.summary-strip { display: flex; gap: 15px; margin-bottom: 20px; flex-wrap: wrap; }
.summary-card {
    flex: 1;
    min-width: 170px;
    color: white;
    padding: 15px 20px;
    border-radius: 10px;
    display: flex;
    flex-direction: column;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}
.summary-pending { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); }
.summary-value   { background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); }
.summary-done    { background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%); }
.summary-number { font-size: 28px; font-weight: bold; line-height: 1.1; }
.summary-money { font-size: 20px; }
.summary-label { font-size: 13px; opacity: 0.95; }
.autogen-page .card {
    border: none;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    border-radius: 10px;
    background: #fff;
    margin-bottom: 20px;
}
.autogen-page .card-header {
    background: #f8f9fa;
    border-bottom: 2px solid #e0e0e0;
    padding: 12px 20px;
    border-radius: 10px 10px 0 0;
}
.autogen-page .card-header h4 { margin: 0; }
.header-flex { display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 8px; }
.autogen-page .card-body { padding: 20px; }
.mapping-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
    gap: 12px;
}
.mapping-card {
    border: 1px solid #e4e8fb;
    border-radius: 8px;
    padding: 12px 15px;
    background: #fafbff;
}
.mapping-card.mapping-broken { border-color: #f5c6cb; background: #fff7f8; }
.mapping-title { font-weight: bold; margin-bottom: 8px; color: #3b4890; }
.mapping-line { display: flex; align-items: center; gap: 8px; padding: 2px 0; font-size: 0.9em; }
.mapping-warn { color: #c0392b; font-size: 0.85em; }
.dc {
    display: inline-block;
    width: 24px;
    text-align: center;
    border-radius: 4px;
    font-size: 0.8em;
    font-weight: bold;
}
.dc-debit { background: #e8f4fd; color: #2b7fd4; }
.dc-credit { background: #fdf1e3; color: #e67e22; }
.generate-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 10px;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 14px 20px;
    border-radius: 10px;
    margin-bottom: 20px;
}
.count-chip {
    background: #667eea;
    color: white;
    padding: 1px 9px;
    border-radius: 10px;
    font-size: 0.8em;
    margin-left: 5px;
}
.pending-table { width: 100%; border-collapse: collapse; min-width: 640px; }
.pending-table th { text-align: left; padding: 8px 10px; border-bottom: 2px solid #667eea; white-space: nowrap; }
.pending-table td { padding: 8px 10px; border-bottom: 1px solid #e9ecef; white-space: nowrap; }
.pending-table .text-right { text-align: right; }
.ref-code { background: #f1f3f9; padding: 2px 8px; border-radius: 5px; font-weight: bold; color: #3b4890; }
.entry-cell { font-size: 0.9em; color: #495057; }
.empty-state { text-align: center; padding: 50px 20px; color: #6c757d; }
.empty-state i { margin-bottom: 15px; opacity: 0.5; color: #43e97b; }
.empty-state h4 { margin: 10px 0; color: #495057; }
</style>
