<?php
/**
 * Journal Entries - rich ledger list
 *
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Journal[]|\Cake\Collection\CollectionInterface $journals
 * @var array $summary      ['total','Draft','Posted','Void','postedDebit','postedCredit']
 * @var string $filterStatus
 */
$this->assign('title', 'Journal Entries');

$money = function ($amount) {
    return 'Rp ' . number_format((float)$amount, 0, ',', '.');
};
$formatDate = function ($value) {
    if ($value instanceof \DateTimeInterface || $value instanceof \Cake\I18n\Date) {
        return $value->format('d M Y');
    }
    $timestamp = $value ? strtotime((string)$value) : false;
    return $timestamp ? date('d M Y', $timestamp) : '-';
};
$journalBadge = function ($status) {
    return $status === 'Posted' ? 'success' : ($status === 'Draft' ? 'warning' : ($status === 'Void' ? 'danger' : 'secondary'));
};
?>

<div class="journals-page">
    <div class="page-header">
        <div>
            <h2><i class="fa fa-book"></i> <?= __('Journal Entries') ?></h2>
            <p class="text-muted"><?= __('General ledger - only Posted entries count in the financial reports') ?></p>
        </div>
        <div class="page-header-actions">
            <?= $this->Html->link('<i class="fa fa-magic"></i> ' . __('Auto-Generate'),
                ['action' => 'autoGenerated'], ['escape' => false, 'class' => 'btn btn-sm btn-primary']) ?>
            <?= $this->Html->link('<i class="fa fa-pencil-square-o"></i> ' . __('Manual Entry'),
                ['action' => 'add'], ['escape' => false, 'class' => 'btn btn-sm btn-success']) ?>
            <?= $this->Html->link('<i class="fa fa-wrench"></i> ' . __('Adjustment'),
                ['action' => 'adjustments'], ['escape' => false, 'class' => 'btn btn-sm btn-outline-secondary']) ?>
            <?= $this->Html->link('<i class="fa fa-bar-chart"></i> ' . __('Reports'),
                ['controller' => 'Reports', 'action' => 'index'],
                ['escape' => false, 'class' => 'btn btn-sm btn-outline-secondary']) ?>
        </div>
    </div>

    <!-- Summary strip -->
    <div class="summary-strip">
        <div class="summary-card summary-total">
            <span class="summary-number"><?= number_format($summary['total']) ?></span>
            <span class="summary-label"><i class="fa fa-book"></i> <?= __('Total Entries') ?></span>
        </div>
        <div class="summary-card summary-posted">
            <span class="summary-number"><?= number_format($summary['Posted']) ?></span>
            <span class="summary-label"><i class="fa fa-check-circle"></i> <?= __('Posted') ?></span>
        </div>
        <div class="summary-card summary-draft">
            <span class="summary-number"><?= number_format($summary['Draft']) ?></span>
            <span class="summary-label"><i class="fa fa-pencil"></i> <?= __('Draft') ?></span>
        </div>
        <div class="summary-card summary-volume">
            <span class="summary-number summary-money"><?= $money($summary['postedDebit']) ?></span>
            <span class="summary-label"><i class="fa fa-money"></i> <?= __('Posted Volume (Debit)') ?></span>
        </div>
    </div>

    <!-- Status filter chips -->
    <div class="filter-chips">
        <span class="chip-label"><i class="fa fa-filter"></i> <?= __('Status:') ?></span>
        <?= $this->Html->link(__('All'), ['action' => 'index'],
            ['class' => 'filter-chip' . ($filterStatus === '' ? ' active' : '')]) ?>
        <?php foreach (['Posted', 'Draft', 'Void'] as $status): ?>
            <?= $this->Html->link(__($status) . ' (' . number_format($summary[$status]) . ')',
                ['action' => 'index', '?' => ['status' => $status]],
                ['class' => 'filter-chip' . ($filterStatus === $status ? ' active' : '')]) ?>
        <?php endforeach; ?>
    </div>

    <?php $rows = iterator_to_array($journals); ?>
    <?php if (!empty($rows)): ?>
        <div class="card">
            <div class="table-scroll-wrapper" style="overflow-x: auto; -webkit-overflow-scrolling: touch;">
                <table class="table rich-table">
                    <thead>
                        <tr>
                            <th class="actions"><?= __('Actions') ?></th>
                            <th><?= $this->Paginator->sort('transaction_date', __('Date')) ?></th>
                            <th><?= $this->Paginator->sort('reference_no', __('Reference')) ?></th>
                            <th><?= __('Description') ?></th>
                            <th class="text-right"><?= $this->Paginator->sort('total_debit', __('Debit')) ?></th>
                            <th class="text-right"><?= $this->Paginator->sort('total_credit', __('Credit')) ?></th>
                            <th><?= __('Balanced') ?></th>
                            <th><?= $this->Paginator->sort('status', __('Status')) ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($rows as $row): ?>
                        <?php $balanced = (float)$row['total_debit'] === (float)$row['total_credit']; ?>
                        <tr>
                            <td class="actions">
                                <?= $this->Html->link('<i class="fa fa-eye"></i>', ['action' => 'view', $row['id']],
                                    ['escape' => false, 'class' => 'btn btn-sm btn-outline-info', 'title' => __('View')]) ?>
                                <?= $this->Html->link('<i class="fa fa-edit"></i>', ['action' => 'edit', $row['id']],
                                    ['escape' => false, 'class' => 'btn btn-sm btn-outline-primary', 'title' => __('Edit')]) ?>
                            </td>
                            <td><?= h($formatDate($row['transaction_date'])) ?></td>
                            <td><strong><?= h($row['reference_no'] ?: ('#' . $row['id'])) ?></strong></td>
                            <td class="desc-cell" title="<?= h($row['description']) ?>"><?= h($row['description'] ?: '-') ?></td>
                            <td class="text-right"><?= $money($row['total_debit']) ?></td>
                            <td class="text-right"><?= $money($row['total_credit']) ?></td>
                            <td>
                                <?php if ($balanced): ?>
                                    <span class="balance-chip balance-ok"><i class="fa fa-check"></i> <?= __('Balanced') ?></span>
                                <?php else: ?>
                                    <span class="balance-chip balance-off" title="<?= __('Debit and credit totals differ') ?>">
                                        <i class="fa fa-exclamation-triangle"></i> <?= $money(abs((float)$row['total_debit'] - (float)$row['total_credit'])) ?>
                                    </span>
                                <?php endif; ?>
                            </td>
                            <td><span class="badge badge-<?= $journalBadge($row['status']) ?>"><?= h($row['status']) ?></span></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="paginator" style="margin-top: 15px;">
            <ul class="pagination">
                <?= $this->Paginator->first('<< ' . __('first')) ?>
                <?= $this->Paginator->prev('< ' . __('previous')) ?>
                <?= $this->Paginator->numbers() ?>
                <?= $this->Paginator->next(__('next') . ' >') ?>
                <?= $this->Paginator->last(__('last') . ' >>') ?>
            </ul>
            <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
        </div>
    <?php else: ?>
        <div class="card">
            <div class="empty-state">
                <i class="fa fa-book fa-4x"></i>
                <h4><?= $filterStatus ? __('No {0} entries.', $filterStatus) : __('No journal entries yet.') ?></h4>
                <p class="text-muted"><?= __('Record debits and credits here - Posted entries feed the Income Statement, Balance Sheet and Cash Flow.') ?></p>
                <div>
                    <?= $this->Html->link('<i class="fa fa-plus-circle"></i> ' . __('Add Entry'),
                        ['action' => 'add'], ['escape' => false, 'class' => 'btn btn-success']) ?>
                    <?php if ($filterStatus): ?>
                        <?= $this->Html->link(__('Show All'), ['action' => 'index'], ['class' => 'btn btn-outline-secondary']) ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>

<style>
.journals-page .page-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 20px;
    flex-wrap: wrap;
    gap: 10px;
}
.journals-page .page-header h2 { margin: 0 0 5px 0; }
.summary-strip { display: flex; gap: 15px; margin-bottom: 20px; flex-wrap: wrap; }
.summary-card {
    flex: 1;
    min-width: 160px;
    color: white;
    padding: 15px 20px;
    border-radius: 10px;
    display: flex;
    flex-direction: column;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}
.summary-total  { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
.summary-posted { background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%); }
.summary-draft  { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); }
.summary-volume { background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); }
.summary-number { font-size: 28px; font-weight: bold; line-height: 1.1; }
.summary-money { font-size: 20px; }
.summary-label { font-size: 13px; opacity: 0.95; }
.filter-chips {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
    background: #fff;
    border-radius: 10px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    padding: 12px 18px;
    margin-bottom: 20px;
}
.chip-label { font-weight: bold; color: #6c757d; font-size: 0.9em; }
.filter-chip {
    padding: 5px 14px;
    border-radius: 15px;
    border: 1.5px solid #e0e0e0;
    background: #f5f5f5;
    color: #546e7a;
    text-decoration: none;
    font-size: 0.88em;
    font-weight: bold;
}
.filter-chip:hover { border-color: #667eea; text-decoration: none; }
.filter-chip.active { background: #667eea; border-color: #667eea; color: #fff; }
.journals-page .card {
    border: none;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    border-radius: 10px;
    background: #fff;
    margin-bottom: 20px;
    overflow: hidden;
}
.rich-table { border-collapse: collapse; width: 100%; min-width: 950px; margin: 0; }
.rich-table thead {
    background: linear-gradient(135deg, rgba(102, 126, 234, 0.15) 0%, rgba(118, 75, 162, 0.15) 100%);
}
.rich-table th { padding: 12px; border-bottom: 2px solid #667eea; white-space: nowrap; text-align: left; }
.rich-table td { padding: 10px 12px; border-bottom: 1px solid #e9ecef; vertical-align: middle; white-space: nowrap; }
.rich-table tbody tr:hover { background: #f8f9ff; }
.rich-table .text-right { text-align: right; }
.rich-table .desc-cell { max-width: 260px; overflow: hidden; text-overflow: ellipsis; }
.rich-table .actions { white-space: nowrap; }
.rich-table th.actions,
.rich-table td.actions {
    position: sticky;
    left: 0;
    z-index: 5;
    width: 1%;
    padding-left: 10px;
    padding-right: 10px;
}
.rich-table th.actions { background: #e9ecfa; z-index: 6; }
.rich-table td.actions { background: #fff; }
.rich-table tbody tr:hover td.actions { background: #f8f9ff; }
.rich-table td.actions .btn { padding: 4px 8px; }
.table-scroll-wrapper.is-scrolled .rich-table th.actions,
.table-scroll-wrapper.is-scrolled .rich-table td.actions {
    border-right: 2px solid #d3d9f5;
    box-shadow: 4px 0 8px -2px rgba(60, 70, 130, 0.18);
}
.balance-chip {
    padding: 3px 10px;
    border-radius: 12px;
    font-size: 0.85em;
    font-weight: bold;
}
.balance-ok { background: #e6f9ee; color: #1e7e42; }
.balance-off { background: #fff8e1; color: #856404; border: 1px solid #ffc107; }
.badge {
    padding: 4px 10px;
    font-size: 11px;
    text-transform: uppercase;
    border-radius: 4px;
    font-weight: bold;
    white-space: nowrap;
}
.badge-success { background: #28a745; color: white; }
.badge-warning { background: #ffc107; color: #333; }
.badge-danger { background: #dc3545; color: white; }
.badge-secondary { background: #6c757d; color: white; }
.empty-state { text-align: center; padding: 50px 20px; color: #6c757d; }
.empty-state i { margin-bottom: 15px; opacity: 0.5; }
.empty-state h4 { margin: 10px 0; color: #495057; }
.empty-state .btn { margin: 5px; }
</style>

<script>
(function () {
    document.querySelectorAll('.journals-page .table-scroll-wrapper').forEach(function (wrapper) {
        var update = function () {
            wrapper.classList.toggle('is-scrolled', wrapper.scrollLeft > 2);
        };
        wrapper.addEventListener('scroll', update, { passive: true });
        update();
    });
})();
</script>
