<?php
/**
 * Manual journal entry / adjustment / edit - dynamic double-entry form
 *
 * Serves add(), adjustments() and edit(). When $isEdit is true the header
 * fields are filled from $journal and the table starts with the entry's own
 * lines instead of two empty ones; everything else, including the balance
 * check, is the same form.
 *
 * @var \App\View\AppView $this
 * @var array $accounts     [id => "code - name (type)"]
 * @var bool $isAdjustment
 * @var bool $isEdit
 * @var \App\Model\Entity\Journal|null $journal
 * @var array $lines        existing journal_details rows, empty for a new entry
 * @var string $pageTitle
 */
$this->assign('title', $pageTitle);

$isEdit = $isEdit ?? false;
$journal = $journal ?? null;
$lines = $lines ?? [];

$journalDate = $isEdit && $journal->transaction_date
    ? (is_string($journal->transaction_date) ? substr($journal->transaction_date, 0, 10) : $journal->transaction_date->format('Y-m-d'))
    : date('Y-m-d');
$journalStatus = $isEdit ? (string)$journal->status : 'Posted';

// A Void entry has to stay available, or reopening one would quietly turn it
// back into a Posted entry.
$statusChoices = ['Posted' => __('Posted'), 'Draft' => __('Draft')];
if ($isEdit) {
    $statusChoices['Void'] = __('Void');
}
?>

<div class="journal-form-page">
    <div class="page-header">
        <div>
            <h2>
                <i class="fa <?= $isEdit ? 'fa-edit' : ($isAdjustment ? 'fa-wrench' : 'fa-pencil-square-o') ?>"></i>
                <?= h($pageTitle) ?>
            </h2>
            <p class="text-muted">
                <?php if ($isEdit) : ?>
                    <?= __('The whole entry is rewritten on save - a line you remove here is removed from the ledger.') ?>
                <?php else : ?>
                    <?= $isAdjustment
                        ? __('Correcting or reclassifying entry - lines must balance (total debit = total credit)')
                        : __('Free-form double-entry - total debit must equal total credit') ?>
                <?php endif; ?>
            </p>
        </div>
        <div class="page-header-actions">
            <?php if ($isEdit) : ?>
                <?= $this->Html->link('<i class="fa fa-eye"></i> ' . __('View Entry'),
                    ['action' => 'view', $journal->id], ['escape' => false, 'class' => 'btn btn-sm btn-outline-secondary']) ?>
            <?php else : ?>
                <?= $this->Html->link('<i class="fa fa-magic"></i> ' . __('Auto-Generate'),
                    ['action' => 'autoGenerated'], ['escape' => false, 'class' => 'btn btn-sm btn-outline-secondary']) ?>
            <?php endif; ?>
            <?= $this->Html->link('<i class="fa fa-book"></i> ' . __('All Journals'),
                ['action' => 'index'], ['escape' => false, 'class' => 'btn btn-sm btn-outline-secondary']) ?>
        </div>
    </div>

    <?= $this->Form->create(null, ['id' => 'journal-form']) ?>

    <?php if ($isEdit && $journalStatus === 'Posted') : ?>
        <div class="posted-warning">
            <i class="fa fa-exclamation-triangle"></i>
            <?= __('This entry is Posted, so it already feeds the financial reports. Editing it changes those figures with no trace of what they were. To correct a posted entry while keeping the history, raise an adjustment instead.') ?>
            <?= $this->Html->link(__('Raise an adjustment'), ['action' => 'adjustments'], ['class' => 'posted-warning-link']) ?>
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h4><i class="fa fa-list"></i> <?= __('Journal Lines') ?></h4></div>
                <div class="card-body">
                    <div class="field-grid-3">
                        <div class="input">
                            <label><?= __('Date') ?></label>
                            <input type="date" name="transaction_date" value="<?= h($journalDate) ?>" required>
                        </div>
                        <div class="input">
                            <label><?= __('Reference') ?> <small class="text-muted">(<?= __('optional') ?>)</small></label>
                            <input type="text" name="reference_no" placeholder="<?= $isAdjustment ? 'ADJ-…' : 'JRN-…' ?>"
                                   value="<?= $isEdit ? h($journal->reference_no) : '' ?>">
                        </div>
                        <div class="input">
                            <label><?= __('Status') ?></label>
                            <select name="status">
                                <?php foreach ($statusChoices as $value => $label) : ?>
                                    <option value="<?= h($value) ?>"<?= $value === $journalStatus ? ' selected' : '' ?>><?= h($label) ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="input">
                        <label><?= __('Description') ?></label>
                        <input type="text" name="description"
                               placeholder="<?= $isAdjustment ? __('e.g. Reclassify ticket cost') : __('e.g. Owner capital injection') ?>"
                               value="<?= $isEdit ? h($journal->description) : '' ?>">
                    </div>

                    <table class="lines-table" id="lines-table">
                        <thead>
                            <tr>
                                <th><?= __('Account') ?></th>
                                <th class="col-note"><?= __('Note') ?></th>
                                <th class="col-amount"><?= __('Debit') ?></th>
                                <th class="col-amount"><?= __('Credit') ?></th>
                                <th class="col-x"></th>
                            </tr>
                        </thead>
                        <tbody id="lines-body">
                            <!-- rows injected by JS -->
                        </tbody>
                        <tfoot>
                            <tr class="totals-row">
                                <td colspan="2" class="text-right"><strong><?= __('Totals') ?></strong></td>
                                <td class="col-amount"><strong id="total-debit">Rp 0</strong></td>
                                <td class="col-amount"><strong id="total-credit">Rp 0</strong></td>
                                <td></td>
                            </tr>
                            <tr class="balance-row">
                                <td colspan="5">
                                    <span id="balance-badge" class="balance-badge balance-off">
                                        <i class="fa fa-exclamation-triangle"></i> <?= __('Not balanced') ?>
                                    </span>
                                </td>
                            </tr>
                        </tfoot>
                    </table>

                    <button type="button" class="btn btn-sm btn-outline-secondary" id="add-line">
                        <i class="fa fa-plus"></i> <?= __('Add Line') ?>
                    </button>

                    <div class="form-actions">
                        <button type="submit" class="btn btn-success btn-lg" id="save-btn" disabled>
                            <i class="fa fa-save"></i> <?= $isEdit ? __('Save Changes') : __('Save Entry') ?>
                        </button>
                        <?= $this->Html->link(__('Cancel'),
                            $isEdit ? ['action' => 'view', $journal->id] : ['action' => 'index'],
                            ['class' => 'btn btn-outline-secondary btn-lg']) ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card">
                <div class="card-header"><h4><i class="fa fa-info-circle"></i> <?= __('Double-Entry Rules') ?></h4></div>
                <div class="card-body">
                    <ul class="guide-list">
                        <li><i class="fa fa-check text-success"></i> <?= __('Every entry needs at least one debit and one credit line.') ?></li>
                        <li><i class="fa fa-check text-success"></i> <?= __('Total debit must equal total credit - the Save button stays locked until it balances.') ?></li>
                        <li><i class="fa fa-check text-success"></i> <?= __('A line is either a debit or a credit, not both.') ?></li>
                        <li><i class="fa fa-info-circle text-info"></i> <?= __('Posted entries feed the financial reports; Draft ones do not.') ?></li>
                    </ul>
                    <?php if ($isAdjustment): ?>
                        <div class="adj-note">
                            <i class="fa fa-wrench"></i>
                            <?= __('Adjustments get an ADJ- reference and are used to correct or reclassify earlier entries.') ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?= $this->Form->end() ?>
</div>

<script>
(function () {
    // JSON_HEX_TAG matters: an account name containing a closing script tag
    // would otherwise end this element in the middle of the data. The tag is
    // described rather than written here for exactly the same reason - a
    // browser ends the element at that sequence wherever it appears, comment
    // or not.
    var accounts = <?= json_encode($accounts, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>;
    var existing = <?= json_encode($lines, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>;
    var body = document.getElementById('lines-body');
    var lineIndex = 0;

    function accountSelect(name) {
        var html = '<select name="' + name + '" required><option value="">— <?= __('Account') ?> —</option>';
        for (var id in accounts) {
            html += '<option value="' + id + '">' + accounts[id].replace(/"/g, '&quot;') + '</option>';
        }
        return html + '</select>';
    }

    function addLine(line) {
        var i = lineIndex++;
        var tr = document.createElement('tr');
        tr.innerHTML =
            '<td>' + accountSelect('lines[' + i + '][chart_of_account_id]') + '</td>' +
            '<td class="col-note"><input type="text" name="lines[' + i + '][description]" class="line-note" placeholder="<?= __('optional') ?>"></td>' +
            '<td class="col-amount"><input type="number" min="0" step="any" name="lines[' + i + '][debit]" class="amt amt-debit" placeholder="0"></td>' +
            '<td class="col-amount"><input type="number" min="0" step="any" name="lines[' + i + '][credit]" class="amt amt-credit" placeholder="0"></td>' +
            '<td class="col-x"><button type="button" class="line-remove" title="<?= __('Remove') ?>">&times;</button></td>';
        body.appendChild(tr);

        if (line) {
            tr.querySelector('select').value = line.chart_of_account_id;
            var d = parseFloat(line.debit) || 0;
            var c = parseFloat(line.credit) || 0;
            if (d) { tr.querySelector('.amt-debit').value = d; }
            if (c) { tr.querySelector('.amt-credit').value = c; }
            tr.querySelector('.line-note').value = line.description || '';
        }

        recalc();
    }

    function rp(n) { return 'Rp ' + (Math.round(n) || 0).toLocaleString('id-ID'); }

    function recalc() {
        var debit = 0, credit = 0;
        body.querySelectorAll('tr').forEach(function (tr) {
            var d = parseFloat(tr.querySelector('.amt-debit').value) || 0;
            var c = parseFloat(tr.querySelector('.amt-credit').value) || 0;
            debit += d; credit += c;
        });
        document.getElementById('total-debit').textContent = rp(debit);
        document.getElementById('total-credit').textContent = rp(credit);
        var badge = document.getElementById('balance-badge');
        var lineCount = body.querySelectorAll('tr').length;
        // Compared in cents, the way the controller compares them
        // (round($x, 2)); rounding to whole rupiah here would unlock Save on an
        // entry the server then rejects.
        var balanced = debit > 0 && Math.round(debit * 100) === Math.round(credit * 100) && lineCount >= 2;
        badge.className = 'balance-badge ' + (balanced ? 'balance-ok' : 'balance-off');
        badge.innerHTML = balanced
            ? '<i class="fa fa-check"></i> <?= __('Balanced') ?>'
            : '<i class="fa fa-exclamation-triangle"></i> <?= __('Not balanced') ?> (' + rp(Math.abs(debit - credit)) + ' <?= __('off') ?>)';
        document.getElementById('save-btn').disabled = !balanced;
    }

    // Debit and credit are mutually exclusive per line
    body.addEventListener('input', function (e) {
        if (e.target.classList.contains('amt-debit') && e.target.value) {
            e.target.closest('tr').querySelector('.amt-credit').value = '';
        } else if (e.target.classList.contains('amt-credit') && e.target.value) {
            e.target.closest('tr').querySelector('.amt-debit').value = '';
        }
        recalc();
    });
    body.addEventListener('click', function (e) {
        if (e.target.classList.contains('line-remove')) {
            e.target.closest('tr').remove();
            recalc();
        }
    });
    // Wrapped: a click handler is called with the Event, which addLine would
    // read as a line to fill in.
    document.getElementById('add-line').addEventListener('click', function () {
        addLine();
    });

    if (existing && existing.length) {
        existing.forEach(function (line) {
            addLine(line);
        });
    } else {
        // A new entry starts with two lines (one debit, one credit)
        addLine();
        addLine();
    }
})();
</script>

<style>
.journal-form-page .page-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 20px;
    flex-wrap: wrap;
    gap: 10px;
}
.journal-form-page .page-header h2 { margin: 0 0 5px 0; }
.journal-form-page .card {
    border: none;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    margin-bottom: 20px;
    border-radius: 10px;
    background: #fff;
}
.journal-form-page .card-header {
    background: #f8f9fa;
    border-bottom: 2px solid #e0e0e0;
    font-weight: bold;
    padding: 12px 20px;
    border-radius: 10px 10px 0 0;
}
.journal-form-page .card-header h4 { margin: 0; }
.journal-form-page .card-body { padding: 20px; }
.field-grid-3 {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 0 12px;
}
@media (max-width: 640px) { .field-grid-3 { grid-template-columns: 1fr; } }
.journal-form-page .input { margin-bottom: 15px; }
.journal-form-page label { font-weight: bold; display: block; margin-bottom: 5px; color: #495057; font-size: 0.9em; }
.journal-form-page input[type="text"],
.journal-form-page input[type="date"],
.journal-form-page input[type="number"],
.journal-form-page select {
    width: 100%;
    padding: 9px 11px;
    border: 1px solid #ced4da;
    border-radius: 8px;
    background: #fff;
    font-size: 14px;
    font-family: inherit;
    box-sizing: border-box;
}
.journal-form-page input:focus, .journal-form-page select:focus {
    outline: none;
    border-color: #667eea;
    box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.15);
}
.lines-table { width: 100%; border-collapse: collapse; margin: 10px 0 15px; }
.lines-table th {
    text-align: left;
    padding: 8px;
    border-bottom: 2px solid #667eea;
    font-size: 0.85em;
    color: #495057;
}
.lines-table td { padding: 6px 8px; vertical-align: middle; }
.lines-table .col-amount { width: 140px; text-align: right; }
.lines-table .col-note { width: 190px; }
.lines-table .line-note { font-size: 13px; }
.lines-table .col-x { width: 36px; }
.lines-table input[type="number"] { text-align: right; }
.line-remove {
    border: none;
    background: #fdeaea;
    color: #c0392b;
    width: 28px;
    height: 28px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
    line-height: 1;
}
.line-remove:hover { background: #c0392b; color: #fff; }
.totals-row td { border-top: 2px solid #e0e0e0; padding-top: 10px; }
.totals-row .text-right { text-align: right; }
.balance-badge {
    display: inline-block;
    padding: 6px 14px;
    border-radius: 15px;
    font-size: 0.9em;
    font-weight: bold;
}
.balance-ok { background: #e6f9ee; color: #1e7e42; }
.balance-off { background: #fff8e1; color: #856404; }
.form-actions { display: flex; gap: 10px; margin-top: 15px; flex-wrap: wrap; }
#save-btn:disabled { opacity: 0.5; cursor: not-allowed; }
.guide-list { list-style: none; padding: 0; margin: 0; }
.guide-list li { padding: 6px 0; color: #495057; }
.guide-list i { width: 20px; }
.adj-note {
    margin-top: 12px;
    padding: 10px 14px;
    background: #fff8e1;
    border: 1px solid #ffe082;
    border-radius: 8px;
    color: #856404;
    font-size: 0.9em;
}
.posted-warning {
    display: flex;
    align-items: baseline;
    flex-wrap: wrap;
    gap: 8px;
    margin-bottom: 18px;
    padding: 12px 16px;
    background: #fff4f2;
    border: 1px solid #f3c2b8;
    border-left: 4px solid #e5533d;
    border-radius: 8px;
    color: #8a2c1b;
    font-size: 0.92em;
    line-height: 1.5;
}
.posted-warning-link {
    font-weight: 600;
    color: #8a2c1b;
    text-decoration: underline;
    white-space: nowrap;
}
.text-success { color: #28a745; }
.text-info { color: #17a2b8; }
</style>
